import { VerticalBox, HorizontalBox, ScrollView } from "std-widgets.slint";
import { TodoLogic } from "./todo_logic.slint";
import { TaskComponent } from "./task.slint";
import { Task } from "./task.struct.slint";
import { AddTaskComponent } from "./add_task.slint";

export component NoteComponent inherits VerticalBox {
    in property <length> parent-width;
    in property <length> parent-height;
    in-out property <string> list-name <=> TodoLogic.list-name;
    in-out property <[Task]> task-list <=> TodoLogic.task-list;

    x: (parent-width - self.width) / 2;
    y: (parent-height - self.height) / 2;
    padding: 0;

    Rectangle {
        padding: 0;
        border-radius: 12px;
        background: #4c4c61;
        width: parent.width;
        height: parent.height;

        VerticalBox {
            width: parent.width;
            height: parent.height;
            padding-top: 15px;
            padding-bottom: 15px;
            padding-left: 15px;
            padding-right: 15px;
            spacing: 15px;
            alignment: start;

            TextInput {
                font-weight: 400;
                color: #FFFFEF;
                font-size: 22px;
                text: root.list-name;
                width: parent.width - 30px;
                edited => {
                    TodoLogic.update-list-name(self.text);
                }
            }

            Rectangle {
                width: parent.width - 30px;
                border-radius: 2px;
                height: 3px;
                background: #FFFFEF;
            }

            ScrollView {
                padding: 0;
                width: parent.width;
                height: parent.height - 73px;
                viewport-width: parent.width - 30px;
                viewport-height: root.task-list.length * 65px + 60px;
                for task in root.task-list: TaskComponent {
                    width: parent.width - 30px;
                    y: task.id * 65px;
                    task: task;
                }

                AddTaskComponent {
                    width: parent.width - 30px;
                    height: 45px;
                    y: root.task-list.length * 65px;
                }
            }
        }
    }
}
