import { TodoLogic } from "./todo.logic.slint";
import { HorizontalBox, CheckBox, VerticalBox } from "std-widgets.slint";
import { Task } from "./task.struct.slint";

export component TaskComponent inherits Rectangle {
    in-out property <Task> task;
    border-radius: 12px;
    height: 50px;
    background: #404054;
    HorizontalBox {
        padding: 15px;
        alignment: start;
        spacing: 10px;

        check-box := CheckBox {
            checked: task.complete;
            toggled => {
                root.task.complete = self.checked;
                TodoLogic.update-task(root.task.description, self.checked, root.task.id);
            }
        }

        description := TextInput {
            width: root.width - 100px;
            text: task.description;
            font-size: 16px;
            edited => {
                root.task.description = self.text;
                TodoLogic.update-task(self.text, root.task.complete, root.task.id);
            }
        }

        trash-can := Image {
            source: @image-url("../assets/delete.svg");
            colorize: #4c4c61;
            animate colorize {
                duration: 150ms;
                easing: ease-in-out;
            }

            trash-touch := TouchArea {
                width: parent.width;
                height: parent.height;

                clicked => {
                    TodoLogic.remove-task(root.task.id);
                }
            }

            states [
                hover-trash when trash-touch.has-hover: {
                    trash-can.colorize: #e64e4e;
                }
                unhover-trash when !trash-touch.has-hover: {
                    trash-can.colorize: #4c4c61;
                }
            ]
        }
    }
}
